BASIC:
  SEED: 26
  BACKUP_CODES: True
  BACKUP_LIST: ['lib', 'tools_cam', 'configs']
  NUM_WORKERS: 6
  PATCH_SIZE: 16
  GAMMA: 1.0
  OUTPUT_DIR: 'output'

MODEL:
  ARCH: deconv
  CAM_THR: 0.5
  TOP_K: 1

DATA:
  DATASET: cub_feat
  DATADIR: /home/xujy/Work/Dataset/CUB_200_2011
  NUM_CLASSES: 200
  RESIZE_SIZE : 256
  CROP_SIZE : 256
  LOC_SIZE : 256
  IMAGE_MEAN : [0.485, 0.456, 0.406]
  IMAGE_STD : [0.229, 0.224, 0.225]
  MASK_SIZE: 15

TRAIN:
  BATCH_SIZE: 256
  OPTIMIZER: 'adam'

TEST:
  BATCH_SIZE: 256
  SAVE_BOXED_IMAGE: False

SOLVER:
  START_LR: 0.004
  LR_STEPS: [10,12]
  NUM_EPOCHS: 20
  LR_FACTOR: 0.1
  MUMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

CUDNN:
  BENCHMARK: False
  DETERMINISTIC: True
  ENABLE: True
